# -*- coding: utf-8 -*-
"""GenStory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UrXmTT2Vn5OxJgaZDlgYQoUzn4ywEAhB
"""

# ---------------------------------------------------------------
# Install dependencies
# ---------------------------------------------------------------
!pip install -q openai-whisper transformers accelerate diffusers

# ---------------------------------------------------------------
# Imports & Config
# ---------------------------------------------------------------
import os
import re
import gc
import json
import torch
import whisper
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from pathlib import Path
from transformers import pipeline as hf_pipeline
from diffusers import StableDiffusionPipeline
from google.colab import userdata

# --- Config ---
TEST_MODE     = False   # True = skip Whisper, use TEST_TEXT below
#TEST_TEXT     = "Once upon a time, a big lion was sleeping soundly in the sun. A little mouse started playing on him, waking the lion up. The lion caught the mouse and was going to eat him Please let me go, said the mouse. Maybe I can help you one day. The lion laughed, but he let the mouse go. A few days later, the lion got caught in a hunter's net. He roared loudly, trying to escape."
TEST_TEXT = "There was a old villager. He was illiterate. He did not know how to read and write. He often saw people wearing spectacles for reading books or papers. He thought If I have spectacles, I can also read like these people. I must go to town and buy a pair of spectacles for myself. So one day he went to a town. He entered a spectacles shop He asked the shopkeeper for a pair of spectacles for reading. The shopkeeper gave him various pairs of spectacles and abook. The villager tried all the spectacles one by one. But he could not read anything."
AUDIO_PATH    = "/content/drive/MyDrive/dataset/hinglish_1.mp3"  # used only if TEST_MODE = False
OUTPUT_FOLDER = "/content/output"
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

HF_TOKEN = userdata.get("HF_TOKEN")

print("✅ Config loaded.")
print(f"   TEST_MODE     : {TEST_MODE}")
print(f"   OUTPUT_FOLDER : {OUTPUT_FOLDER}")
print(f"   HF_TOKEN      : {'found ✓' if HF_TOKEN else 'MISSING ✗ — add it to Colab Secrets'}")

# ---------------------------------------------------------------
# CELL 3 — Memory Utility
# ---------------------------------------------------------------
def flush():
    gc.collect()
    torch.cuda.empty_cache()

print("✅ flush() ready.")

# ================================================================
# PHASE 1 — WHISPER
# Skipped if TEST_MODE = True
# ================================================================

# ---------------------------------------------------------------
# CELL 4 — Whisper: Transcribe & Translate to English
# ---------------------------------------------------------------
if TEST_MODE:
    translated_text = TEST_TEXT
    print("⏭️  TEST_MODE ON — skipping Whisper.")
    print(f"\n📝 Input text:\n{translated_text}\n")

else:
    print("🎙️  Loading Whisper medium...")
    whisper_model = whisper.load_model("medium").to("cuda")
    print("✅ Whisper loaded.\n")

    print(f"🎙️  Transcribing: {AUDIO_PATH}")
    result = whisper_model.transcribe(audio=AUDIO_PATH, task="translate")
    translated_text = result["text"].strip()

    del whisper_model
    flush()
    print("✅ Whisper unloaded.\n")

    print(f"📝 Translated text:\n{translated_text}\n")

# ================================================================
# PHASE 2 — LLAMA
# 3 calls total: 1 story structure + 1 visual extraction per scene
# ================================================================

# ---------------------------------------------------------------
# CELL 5 — Llama: Prompts
# ---------------------------------------------------------------
STORY_PROMPT = """You are a children's story writer for kids.
Given an input text, do exactly two things:

1. Rewrite it as a warm, simple children's story (6-8 lines total).
   Use easy words, a positive tone, and a clear beginning and end.

2. Split the story into exactly 2 scenes.
   Scene 1 = the setup or beginning.
   Scene 2 = the key moment or resolution.
   Each scene should be 2-3 lines.

Respond in this EXACT format with no extra text:
FULL_STORY:
[6-8 line story]
SCENE_1:
[2-3 lines]
SCENE_2:
[2-3 lines]"""

# Update line 28 in Cell 5
VISUAL_PROMPT = """You are a visual scene describer.
Given a scene, describe the SINGLE main subject and their action in one short sentence.

Rules:
1. No labels like "Character" or "Setting".
2. Maximum 12 words.
3. Focus on one subject only.

Example Input: A big lion was sleeping soundly in the sun.
Example Output: a majestic lion sleeping soundly in the sun

Example Input: The little mouse heard the lion and ran to help.
Example Output: a tiny brown mouse running quickly through grass"""

print("✅ Llama prompts defined.")

# ---------------------------------------------------------------
# CELL 6 — Llama: Parsers & SD Prompt Builder
# ---------------------------------------------------------------
def call_llama(pipe, system, user, max_tokens=450):
    messages = [
        {"role": "system", "content": system},
        {"role": "user",   "content": user}
    ]
    out = pipe(messages, max_new_tokens=max_tokens, temperature=0.7)
    return out[0]["generated_text"][-1]["content"].strip()


def parse_story(raw):
    try:
        full = re.search(r"FULL_STORY:\s*(.*?)(?=SCENE_1:|$)", raw, re.DOTALL | re.IGNORECASE)
        sc1  = re.search(r"SCENE_1:\s*(.*?)(?=SCENE_2:|$)",    raw, re.DOTALL | re.IGNORECASE)
        sc2  = re.search(r"SCENE_2:\s*(.*?)$",                 raw, re.DOTALL | re.IGNORECASE)

        full_story = full.group(1).strip() if full else raw.strip()
        scene_1    = sc1.group(1).strip()  if sc1  else full_story[:len(full_story)//2]
        scene_2    = sc2.group(1).strip()  if sc2  else full_story[len(full_story)//2:]

        if not scene_1 or not scene_2:
            raise ValueError("Empty scene after parsing.")

        return full_story, scene_1, scene_2

    except Exception as e:
        print(f"⚠️  Story parse warning: {e} — using fallback split.")
        half = len(raw) // 2
        return raw, raw[:half].strip(), raw[half:].strip()


def parse_visuals(raw):
    # If the model gives a single line like "A lion in the jungle"
    # we just use the whole line as the 'character' and leave setting empty
    # or split by a comma if present.
    try:
        if not raw.strip():
            raise ValueError("Empty output")

        # Simplistic split: assume "Character, Setting"
        if "," in raw:
            parts = raw.split(",", 1)
            return parts[0].strip(), parts[1].strip()

        return raw.strip(), "" # Use whole line as character description

    except Exception as e:
        print(f"⚠️ Visual parse warning: {e} — using generic fallback.")
        return "young child with dark hair, simple tunic, small satchel", "peaceful countryside"


def build_sd_prompt(description):
    # This takes the raw output from Llama and adds the trigger at the end
    return f"{description} ghibli style"

print("✅ Parsers and SD prompt builder ready.")

# ---------------------------------------------------------------
# CELL 7 — Llama: Load + Run All 3 Calls
# ---------------------------------------------------------------
print("🤖 Loading Llama 3.2 3B Instruct...")
llama = hf_pipeline(
    "text-generation",
    model="meta-llama/Llama-3.2-3B-Instruct",
    device_map="auto",
    torch_dtype=torch.float16,
    token=HF_TOKEN
)
print("✅ Llama loaded.\n")

# --- Call 1: Story Structuring ---
print("📖 Call 1/3 — Structuring story...")
raw_story = call_llama(llama, STORY_PROMPT, f"Input text:\n{translated_text}")

full_story, scene_1_text, scene_2_text = parse_story(raw_story)

print(f"\n📖 Full story:\n{full_story}")
print(f"\n🎬 Scene 1:\n{scene_1_text}")
print(f"\n🎬 Scene 2:\n{scene_2_text}\n")

# --- Call 2: Visuals for Scene 1 ---
print("🎨 Call 2/3 — Extracting visuals for Scene 1...")
description_1 = call_llama(llama, VISUAL_PROMPT, f"Scene: \n{scene_1_text}", max_tokens=30)
sd_prompt_1 = build_sd_prompt(description_1)

print(f"   Desc : {description_1}")
print(f"   SD Prompt : {sd_prompt_1}\n")

# --- Call 3: Visuals for Scene 2 ---
print("🎨 Call 3/3 — Extracting visuals for Scene 2...")
description_2 = call_llama(llama, VISUAL_PROMPT, f"Scene: \n{scene_2_text}", max_tokens=30)
sd_prompt_2 = build_sd_prompt(description_2)

print(f"   Desc : {description_2}")
print(f"   SD Prompt : {sd_prompt_2}\n")

del llama
flush()
print("✅ Llama unloaded.\n")

# ================================================================
# PHASE 3 — STABLE DIFFUSION
# ================================================================

# ---------------------------------------------------------------
# CELL 8 — SD: Load Ghibli Diffusion + Generate Images
# ---------------------------------------------------------------


print("🖼️  Loading Ghibli Diffusion...")
sd_pipe = StableDiffusionPipeline.from_pretrained(
    "nitrosocke/Ghibli-Diffusion",
    torch_dtype=torch.float16
).to("cuda")
sd_pipe.enable_attention_slicing()
print("✅ Ghibli Diffusion loaded.\n")

negative_prompt = "soft blurry, dithered, low quality, photorealistic, 3d render, deformed"

generator = torch.Generator(device="cuda").manual_seed(121)
image_paths = []
for i, sd_prompt in enumerate([sd_prompt_1, sd_prompt_2], start=1):
    print(f"🖼️  Generating Scene {i}/2...")
    image = sd_pipe(
        prompt=sd_prompt,
        negative_prompt=negative_prompt,
        num_inference_steps=60,
        width=512,
        height=512,
        guidance_scale=8.5,
        #generator=generator
    ).images[0]

    path = os.path.join(OUTPUT_FOLDER, f"scene_{i}.png")
    image.save(path)
    image_paths.append(path)
    print(f"   ✅ Saved: {path}")

del sd_pipe
flush()
print("\n✅ Ghibli Diffusion unloaded.")

# ================================================================
# OUTPUT — Display + Save
# ================================================================

# ---------------------------------------------------------------
# CELL 9 — Display story and images inline
# ---------------------------------------------------------------
print("\n" + "="*55)
print("GENERATED STORY")
print("="*55)
print(full_story)
print("="*55)

fig, axes = plt.subplots(1, 2, figsize=(12, 6))
for ax, path, scene_text in zip(axes, image_paths, [scene_1_text, scene_2_text]):
    img = mpimg.imread(path)
    ax.imshow(img)
    # Truncate scene text for the subtitle
    ax.set_title(scene_text[:60] + "...", fontsize=8, wrap=True)
    ax.axis("off")
plt.suptitle("KidStory — Generated Scenes", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

# ---------------------------------------------------------------
# CELL 10 — Save metadata
# ---------------------------------------------------------------
metadata = {
    "input_text": translated_text,
    "full_story": full_story,
    "scenes": [
        {
            "scene_number": 1,
            "text":       scene_1_text,
            "character":  char_1,
            "setting":    sett_1,
            "sd_prompt":  sd_prompt_1,
            "image_path": image_paths[0]
        },
        {
            "scene_number": 2,
            "text":       scene_2_text,
            "character":  char_2,
            "setting":    sett_2,
            "sd_prompt":  sd_prompt_2,
            "image_path": image_paths[1]
        }
    ]
}

json_path = os.path.join(OUTPUT_FOLDER, "output.json")
with open(json_path, "w", encoding="utf-8") as f:
    json.dump(metadata, f, indent=2, ensure_ascii=False)

print(f"\n✅ Metadata saved: {json_path}")
print("\n🎉 Pipeline complete!")